# Generated by Django 4.2.6 on 2023-11-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InformationOfCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("temperatyra", models.IntegerField(default=0)),
                ("Ves", models.IntegerField(default=0)),
                ("Obiom", models.IntegerField(default=0)),
                ("kolvoMest", models.IntegerField(default=0)),
                (
                    "stoimostGruza",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=2, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("t", "Tent"),
                            ("i", "Izoterma"),
                            ("r", "Refrezirator"),
                        ],
                        default=0,
                        max_length=50,
                    ),
                ),
                ("gabariti", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Zayaka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("closing_time", models.DateTimeField()),
                ("kolishestvo", models.IntegerField(default=1)),
                ("pogruzka", models.TextField()),
                ("razgruzka", models.TextField()),
                (
                    "gruz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gruz",
                        to="main.informationofcargo",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport",
                        to="main.transport",
                    ),
                ),
            ],
        ),
    ]
